@echo off
setlocal EnableExtensions EnableDelayedExpansion

set ROOT_DIR=%~dp0
cd /d "%ROOT_DIR%"

:: --- Configuration (Hardcoded) ---
set "JAVA_HOME=C:\Program Files\Java\jdk-11.0.12"
set "GRADLE_USER_HOME=F:/software/Android-New-Gradle-Cache/.gradle"
set "ADB_PATH=D:\Android-Sdk\sdk\platform-tools\adb.exe"
set "ANDROID_SDK_ROOT=D:\Android-Sdk\sdk"

:: --- App Configuration ---
set "PACKAGE_NAME=leo.openautojs.autojs"
set "MAIN_ACTIVITY=org.autojs.autojs.ui.splash.SplashActivity"

:: --- 签名配置 (Sign Config) ---
:: 注意：如果你的签名文件有后缀名（比如 1.jks 或 1.keystore），请在下方补全后缀
set "KEYSTORE_FILE=%ROOT_DIR%sign\1.jks"
set "KEYSTORE_PASS=123456"
set "KEY_ALIAS=alias"
set "KEY_PASS=123456"

echo [VERIFY] Environment Configured:
echo   JAVA_HOME=%JAVA_HOME%
echo   GRADLE_USER_HOME=%GRADLE_USER_HOME%
echo   ADB_PATH=%ADB_PATH%
echo   ANDROID_SDK_ROOT=%ANDROID_SDK_ROOT%
echo   KEYSTORE_FILE=%KEYSTORE_FILE%

:: --- Auto-Generate local.properties for Portability ---
:: Escape backslashes for properties file
set "SDK_DIR_ESCAPED=%ANDROID_SDK_ROOT:\=\\%"
(
  echo ## This file is automatically generated by run_app_rtn.bat
  echo sdk.dir=%SDK_DIR_ESCAPED%
) > "local.properties"

:: 创建 apks 文件夹用于存放生成的正式版签名包
set "OUT_APKS_DIR=%ROOT_DIR%apks"
if not exist "%OUT_APKS_DIR%" mkdir "%OUT_APKS_DIR%"

:: --- Step1: Gradle assembleRelease 注入签名参数 ---
echo [VERIFY] Step1: Gradle assembleRelease (Signed)
call "%ROOT_DIR%gradlew.bat" :app:assembleRelease ^
  -Pandroid.injected.signing.store.file="%KEYSTORE_FILE%" ^
  -Pandroid.injected.signing.store.password="%KEYSTORE_PASS%" ^
  -Pandroid.injected.signing.key.alias="%KEY_ALIAS%" ^
  -Pandroid.injected.signing.key.password="%KEY_PASS%"

if errorlevel 1 (
  echo [VERIFY] assembleRelease failed
  pause
  exit /b 101
)

:: --- 查找生成的 Release APK ---
:: 依据你提供的 debug 路径，release 产物一般在 common\release 目录下
set "RELEASE_BUILD_DIR=%ROOT_DIR%app\build\outputs\apk\common\release"
set "EXPECTED_APK_NAME=app-common-arm64-v8a-release.apk"

if exist "%RELEASE_BUILD_DIR%\%EXPECTED_APK_NAME%" (
    set "BUILT_APK_PATH=%RELEASE_BUILD_DIR%\%EXPECTED_APK_NAME%"
) else (
    :: 如果名字不完全匹配，则在该目录下尝试寻找任意 .apk 文件作为备选
    for %%F in ("%RELEASE_BUILD_DIR%\*.apk") do (
        set "BUILT_APK_PATH=%%F"
        goto :found_built_apk
    )
)

:found_built_apk
if not exist "!BUILT_APK_PATH!" (
  echo [VERIFY] Release APK not found in %RELEASE_BUILD_DIR%
  pause
  exit /b 102
)

:: --- 拷贝 APK 到 apks 目录 ---
echo [VERIFY] Copying signed APK to %OUT_APKS_DIR%
copy /Y "!BUILT_APK_PATH!" "%OUT_APKS_DIR%\"

:: 提取文件名以获得最终 APK 完整路径
for %%F in ("!BUILT_APK_PATH!") do set "APK_FILENAME=%%~nxF"
set "APK_PATH=%OUT_APKS_DIR%\!APK_FILENAME!"

echo [VERIFY] Final Signed APK is ready at: !APK_PATH!

:: --- Prepare ADB ---
set "ADB_EXEC=%ADB_PATH%"
if not exist "!ADB_EXEC!" (
     echo [VERIFY] Configured ADB_PATH not found: !ADB_EXEC!
     pause
     exit /b 0
)

for /f "tokens=1" %%i in ('"!ADB_EXEC!" get-state 2^>nul') do set ADB_STATE=%%i
if /i not "!ADB_STATE!"=="device" (
  echo [VERIFY] no device, skip install/launch
  pause
  exit /b 0
)

echo [VERIFY] Step2: adb install
"!ADB_EXEC!" install -r "!APK_PATH!"
if errorlevel 1 (
  echo [VERIFY] adb install failed
  pause
  exit /b 103
)

echo [VERIFY] Step3: adb launch
"!ADB_EXEC!" shell am start -n %PACKAGE_NAME%/%MAIN_ACTIVITY%
if errorlevel 1 (
  echo [VERIFY] adb launch failed
  pause
  exit /b 104
)

echo [VERIFY] OK
pause
exit /b 0